sudo: required
addons:
  chrome: stable

language: node_js
node_js:
- "8"

branches:
  only:
  - master

before_script:
- npm install -g @angular/cli

script:
- npm install -g angular-cli-ghpages
- ng build --project=main --prod --base-href '/'
