sudo: required
addons:
  chrome: stable

language: node_js
node_js:
- "8"

branches:
  only:
  - master

before_script:
- npm install -g @angular/cli
- npm build_app
- npm build_admin


script:
- npm install -g angular-cli-ghpages
- ng build --prod --base-href '/'
